import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import 'semantic-ui-css/semantic.min.css'
import Top from "../component/Top";
import Footer from "../component/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <Top />
        {children}
      </body>
      {/* <body>
        <div style={{ width: 1000, margin: "0 auto" }}>
          <Top />
          {children}
          <Footer />
        </div>      
      </body> */}
    </html>
  );
}
